POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "name": "Rômulo Franco",
  "email": "romulojosefranco@gmail.com",
  "password": "987321"
}

###

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{ 
  "email": "root@mail.com",
  "password": "admin"
}

###

POST http://localhost:3000/recipes HTTP/1.1
Content-Type: application/json
Authorization: 6130122f210a002f10cf94de

{  
  "name": "Ovo mexido",
  "ingredients": "ovo, farinha, temperos e sal a gosto",
  "preparation": "comece a fritar o ovo, coloque o sal, quando ele estiver um pouco de consistencia, jogue os temperos e a farinha, mexa ate ficar um grude gostoso! Pronto.",  
}

###


